version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: juan_payment
      DB_USER: postgres
      DB_PASSWORD: 123
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: juan_payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
